version: '3.8'

services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: auth_mysql
  #   env_file: .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
  #   volumes:
  #     - db_mysql_data:/var/lib/mysql
  #     # - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  auth_server:
    build:
      context: .
      dockerfile: Auth_Server.Dockerfile
    container_name: auth_server
    # depends_on:
    #   mysql:
    #     condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    # restart: unless-stopped

# volumes:
#   db_mysql_data:
